/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.project;

import mini.project.handler.HandphoneHandler;
import mini.project.handler.HomeHandler;
import mini.project.util.Prompt;

public class App{

	public static void main(String[] args) {

		HandphoneHandler handphonehandler = new HandphoneHandler();
		HomeHandler homehandler = new HomeHandler(handphonehandler);

		loop:
			while (true) {
				String command = Prompt.inputString("명령> ");

				switch (command) {
				case "/handphone/add": handphonehandler.add(); break;
				case "/handphone/list": handphonehandler.list(); break;
				case "/home/add": homehandler.add(); break;
				case "/home/list": homehandler.list(); break;
				case "quit":
				case "exit":
					System.out.println("안녕!");
					break loop;
				default:
					System.out.println("실행할 수 없는 명령입니다.");
				}
				System.out.println(); // 이전 명령의 실행을 구분하기 위해 빈 줄 출력
			}

		Prompt.close();
	}
}

